openapi: 3.0.3
info:
  title: Employee - OpenAPI 3.0
  description: |-
    Employee API Spec
  version: 1.0.0
servers:
  - url: api
paths:
  /employee:
    post:
      tags:
        - employee
      summary: Add a new employee
      description: Add a new employee
      operationId: addEmployee
      requestBody:
        description: Create a new employee
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid request
    get:
      tags:
        - employee
      summary: Get all employees
      description: Get all employees
      operationId: getEmployees
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
        '400':
          description: Invalid request
components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: John
        age:
          type: integer
          format: int
          example: 25